
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bildblattbackend-minio
  name: bildblattbackend-minio
  namespace: wordpress-bildblatt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bildblattbackend-minio
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bildblattbackend-minio
    spec:
      containers:
        - env:
            - name: bildblattbackend-minio_DB_HOST 
              value: bildblattbackend-minio-mariadb-service
            - name: bildblattbackend-minio_DB_USER 
              value: bildblattbackend-minio
            - name: bildblattbackend-minio_DB_NAME
              value: bildblattbackend-minio
            - name: bildblattbackend-minio_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-mariacreds
                  key: MARIADB_PASSWORD
          image: minio/minio:latest
          name: bildblattbackend-minio
          command: ["minio", "server", "/data"]
          ports:
            - containerPort: 9000
            - containerPort: 9001
          resources:
            requests:
              memory: "50Mi"
              cpu: "50m"
            limits:
              memory: "500Mi"
              cpu: "500m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bildblattbackend-minio
  name: bildblattbackend-minio-service
  namespace: wordpress-bildblatt
spec:
  ports:
    - name: "bildblattbackend-minio"
      port: 9000
      targetPort: 9000
  selector:
    app: bildblattbackend-minio
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bildblattbackend-minio
  name: bildblattbackend-minio-api-service
  namespace: wordpress-bildblatt
spec:
  ports:
    - name: "bildblattbackend-minio-api"
      port: 9001
      targetPort: 9001
  selector:
    app: bildblattbackend-minio
---